
# Spine Switches
spine:
  defaults:
    platform: cEOS
    bgp_as: 65002
    loopback_ipv4_pool: 192.168.201.0/24
    mlag: false
  nodes:
    - name: spine1-DC2
      id: 11
      mgmt_ip: 192.168.0.14/24
    - name: spine2-DC2
      id: 12
      mgmt_ip: 192.168.0.15/24
    - name: spine3-DC2
      id: 13
      mgmt_ip: 192.168.0.16/24

# Leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    platform: cEOS
    bgp_as: 65200-65299 # Gives a range which will be auto-assigned
    loopback_ipv4_pool: 192.168.201.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.202.0/24 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet3, Ethernet4, Ethernet5] # Leaf uplinks
    uplink_switches: [spine1-DC2, spine2-DC2, spine3-DC2] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.203.0/24 # For the p2p interfaces to chopped up into /31s
    mlag_interfaces: [Ethernet1, Ethernet2] # MLAG peer link
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: true # By default, use MLAG

  node_groups:
    - group: dc2_mlag1
      nodes:
        leaf1-DC2:
          id: 1
          mgmt_ip: 192.168.0.31/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2, Ethernet2]
        leaf2-DC2:
          id: 2
          mgmt_ip: 192.168.0.32/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3]
    - group: dc2_mlag2
      nodes:
        leaf3-DC2:
          id: 3
          mgmt_ip: 192.168.0.33/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4]
        leaf4-DC2:
          id: 4
          mgmt_ip: 192.168.0.34/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5]
    - group: dc2_bl
      nodes:
        borderleaf1-DC2:
          id: 5
          mgmt_ip: 192.168.0.35/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6]
          evpn_route_servers: [spine1-DC2, spine2-DC2, spine3-DC2, spine1-DC1, spine2-DC1, spine3-DC1]
        borderleaf2-DC2:
          id: 6
          mgmt_ip: 192.168.0.36/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7, Ethernet7]
          evpn_route_servers: [spine1-DC2, spine2-DC2, spine3-DC2, spine1-DC1, spine2-DC1, spine3-DC1]
