---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: true

core_interfaces:
  p2p_links:
    - ip: [ 192.168.99.0/31, 192.168.99.1/31 ]
      nodes: [ borderleaf1-DC1, DCI ]
      interfaces: [ Ethernet12, Ethernet1 ]
      include_in_underlay_protocol: true
      as: [ 65104, 65000 ]
    - ip: [ 192.168.99.2/31, 192.168.99.3/31 ]
      nodes: [ borderleaf2-DC1, DCI ]
      interfaces: [ Ethernet12, Ethernet2 ]
      include_in_underlay_protocol: true
      as: [ 65104, 65000 ]
    - ip: [ 192.168.99.4/31, 192.168.99.5/31 ]
      nodes: [ borderleaf1-DC2, DCI ]
      interfaces: [ Ethernet12, Ethernet2 ]
      include_in_underlay_protocol: true
      as: [ 65204, 65000 ]
    - ip: [ 192.168.99.6/31, 192.168.99.7/31 ]
      nodes: [ borderleaf2-DC2, DCI ]
      interfaces: [ Ethernet12, Ethernet2 ]
      include_in_underlay_protocol: true
      as: [ 65204, 65000 ]

p2p_uplinks_mtu: 1500

dns_domain: atd.lab
mgmt_interface: Management0
mgmt_interface_vrf: default
mgmt_gateway: 192.168.0.1


