---
- name: Configure hosts
  hosts: HOSTS_DC1
  tasks:
    - name: Generate Device Configurations and Documentation
      import_role:
        name: arista.avd.eos_cli_config_gen

- name: Deploy fabric to CVP
  hosts: cvp1
  tasks:
    - name: provision CVP with AVD configuration
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'FABRIC'
        configlets_prefix: 'AVD'
        state: present
        execute_tasks: true
        cv_collection: v3
